version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - Snazzah
  open-pull-requests-limit: 15
  target-branch: dev
  commit-message:
    prefix: chore
    include: scope
