<template>
  <div id="settingsPage" class="page">
    <h3>Settings</h3>
    <a v-if="$parent.discordStatus !== 1" class="router-link" @click="$parent.reconnectDiscord">
      <RefreshIcon />
      <span>Restart RPC Clients</span>
    </a>
    <ToggleInput
      v-model="autoCheckPresenceUpdates"
      title="Automatically check for presence updates"
    />
    <ToggleInput
      v-if="autoCheckPresenceUpdates"
      v-model="autoUpdatePresences"
      class="indent"
      title="Auto-update Presences"
      note="Presences will be updated upon startup and hourly."
    />
    <h4>System Startup Behavior</h4>
    <ToggleInput
      v-model="autoLaunch"
      title="Launch on Startup"
    />
    <ToggleInput
      v-model="showWindowOnLaunch"
      title="Show App on Launch"
      note="Turning this off will leave Steemcord in the tray on launch."
    />
    <ToggleInput
      v-model="minimizeToTray"
      title="Minimize to Tray"
      note="Pressing X in the app will leave Steemcord in the tray."
    />
    <h4>Notifications</h4>
    <ToggleInput
      v-model="presenceNotifications"
      title="Presence Notifications"
      note="Presence Auto-Updated, Presence Updates Ready"
    />
    <ToggleInput
      v-model="steamNotifications"
      title="Steam Notifications"
      note="Steam Auto-Login Failed"
    />
    <div v-if="devMode">
      <h4>Developer Settings</h4>
      <TextInput
        ref="dpInput"
        v-model="directoryPoint"
        url
        :default-value="mainDirectoryPoint"
        placeholder="JSON URL..."
        title="Directory Point"
      />
      <NumberInput
        v-model="presencePollInterval"
        :min="60 * 1000" :max="14 * 60 * 60 * 1000"
        :default-value="60 * 60 * 1000"
        title="Presence Polling Interval (milliseconds)"
        note="Changes require an app restart."
      />
      <ToggleInput
        v-model="regenLoginKey"
        :default-value="false"
        title="Auto-renew Login Keys"
        note="Ask Steam for a new login key everytime you automatically log in."
      />
      <DropdownInput
        v-model="machineIDType"
        :default-value="1"
        title="Machine ID Type"
        note="What kind of machine ID will be sent to Steam when logging on? Try this out if Steam logs you out too much."
        :values="[
          'Always Random',
          'Generated by Account Name',
          'Persistent'
        ]"
      />
    </div>
    <h4>Other Settings</h4>
    <ToggleInput
      v-model="devMode"
      title="Developer Mode"
      note="Allows you to develop presences. Compiles and applies as you save!"
    />
  </div>
</template>

<script lang="ts">
import ToggleInput from './components/ToggleInput.vue';
import TextInput from './components/TextInput.vue';
import NumberInput from './components/NumberInput.vue';
import DropdownInput from './components/DropdownInput.vue';
const { remote } = window.require('electron');
const settingsManager = remote.require('./managers/settings');
const directoryPoint = remote.require('./managers/directoryPoint');
const { MAIN_DIRECTORY_POINT } = remote.require('./constants');
// @ts-ignore
import RefreshIcon from './assets/svg/refresh.svg';

function fillComputedSettings(settings: string[]) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const computed: { [key: string]: { get(): any; set(value: any): any; } } = {};
  settings.forEach(key => computed[key] = {
    get() {
      return this.$parent[key];
    },
    set(value: boolean) {
      settingsManager.settings.set(key, value);
      this.$parent.updateSettings();
      return value;
    }
  });
  return computed;
}

export default {
  name: 'Settings',
  components: { ToggleInput, TextInput, NumberInput, DropdownInput, RefreshIcon },
  data() {
    return {
      mainDirectoryPoint: MAIN_DIRECTORY_POINT
    };
  },
  computed: {
    ...fillComputedSettings([
      'devMode',
      'autoLaunch',
      'showWindowOnLaunch',
      'autoUpdatePresences',
      'minimizeToTray',
      'presencePollInterval',
      'autoCheckPresenceUpdates',
      'presenceNotifications',
      'steamNotifications',
      'regenLoginKey',
      'machineIDType'
    ]),
    directoryPoint: {
      get() {
        return directoryPoint.getDirectoryPoint();
      },
      set(value: string) {
        settingsManager.settings.set('directoryPoint', value);
        return value;
      }
    }
  },
  methods: {
    reconnectDiscord() {
      this.$parent.reconnectDiscord();
    }
  }
};
</script>

<style lang="stylus">
#settingsPage
  .indent
    margin-left 20px
</style>