name: Deploy
on:
  push:
    tags:
      - '*'
env:
  NODE_ENV: GITHUB_DEPLOY
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            folder_name: linux-unpacked
            asset_name: linux
          - os: windows-latest
            folder_name: win-unpacked
            asset_name: windows
          - os: macos-latest
            folder_name: mac
            asset_name: mac
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Set Global Folder
        if: matrix.asset_name == 'linux'
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
      - name: Install Dependencies
        run: |
          npm i
          npm i -g typescript rimraf electron-builder
      - name: Prepare to package
        run: npm run init:pkg
      - name: Package
        run: npm run pkg
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      - name: Zip Package
        run: |
          rimraf dist/app
          node util/zip dist/${{ matrix.folder_name }} Steemcord-${{ github.ref }}-${{ matrix.asset_name }}.zip --zip
      - name: Upload packages
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Steemcord-${{ github.ref }}-${{ matrix.asset_name }}.zip
          asset_name: Steemcord-${{ github.ref }}-${{ matrix.asset_name }}
          tag: ${{ github.ref }}